### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by MachineGUN001** [molecularinformatics/roshambo#2]
hi,

thanks for sharing this interesting program.

when I try to install the packge, by following the instruction in readme, some error occured.
the commandline I used
```bash
pip3 install .
```
error info:
```
Processing e:\roshambo-master
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "E:\roshambo-master\setup.py", line 14, in <module>
          raise Exception(f"{var} environment variable not set.")
      Exception: RDBASE environment variable not set.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

could you please provide some suggestions how to fix it?

my OS is windows 10 and python 3.9 version

many thanks,

Best,

**Comment by MachineGUN001** [comment]
thanks for your suggestions, I will set path and try it. thanks
