### ISSUE TITLE
No valid molecules found in input error

### ISSUE THREAD

**Issue by satvikkg** [molecularinformatics/roshambo#7]
Hi, I am getting the following error when I ran the following command in notebooks/data/basic_example directory:
mkdir test/
roshambo --n_confs 0 --ignore_hs --color --sort_by ComboTanimoto --write_to_file --working_dir test/ --gpu_id 0 query.sdf dataset.sdf

Traceback (most recent call last):
  File "/usr/local/bin/roshambo", line 33, in <module>
    sys.exit(load_entry_point('roshambo==0.0.1', 'console_scripts', 'roshambo')())
  File "/usr/local/lib/python3.10/dist-packages/roshambo/cli.py", line 188, in main
    get_similarity_scores(
  File "/usr/local/lib/python3.10/dist-packages/roshambo/api.py", line 106, in get_similarity_scores
    sm = GetSimilarityScores(
  File "/usr/local/lib/python3.10/dist-packages/roshambo/core.py", line 121, in __init__
    ref_mol, _, _ = prepare_mols(
  File "/usr/local/lib/python3.10/dist-packages/roshambo/utilities.py", line 387, in prepare_mols
    rdmols = smiles_to_rdmol(
  File "/usr/local/lib/python3.10/dist-packages/roshambo/utilities.py", line 207, in smiles_to_rdmol
    raise ValueError("No valid molecules found in input.")
ValueError: No valid molecules found in input.

The installation was successful.

**Comment by bcossins** [comment]
Its the way you have set working_dir.
If you don't define "working_dir" and let it go to the default it will work.

**Comment by satvikkg** [comment]
Thanks, It is working now.
